### ISSUE TITLE
google analitycs

### ISSUE THREAD

**Issue by magneto664** [hillipino/Chaturbate-API#1]
Hi can u add google analitycs to all websites. tnx.

**Comment by hillipino** [comment]
Just paste the code in templates.php in the header or footer section

**Comment by magneto664** [comment]
Try do this, and tell me how to fix this error tnx.

2016-04-24 15:25 GMT+01:00 Hillipino <notifications@github.com>:

**Comment by hillipino** [comment]
which error? IF i get some free time ill add in the code and leave an option to define your id

**Comment by hillipino** [comment]
Added the code to both versions, you can either set your tracking id to use analytics or leave it blank to not use it.
